const OAUTH_CLIENT_ID = process.env.REACT_APP_GOOGLE_OAUTH_CLIENT_ID;
const SANITY_PROJECT_ID = process.env.REACT_APP_SANITY_PROJECT_ID;
const SANITY_TOKEN = process.env.REACT_APP_SANITY_TOKEN;
const SANITY_TOKEN_ALL_ACCESS = process.env.REACT_APP_SANITY_TOKEN_ALL_ACCESS;
const SANITY_DATAESET = process.env.REACT_APP_SANITY_DATAESET;
const SANITY_API_VERSION = process.env.REACT_APP_SANITY_API_VERSION;

export {
  OAUTH_CLIENT_ID, 
  SANITY_PROJECT_ID, 
  SANITY_TOKEN,
  SANITY_TOKEN_ALL_ACCESS,
  SANITY_DATAESET,
  SANITY_API_VERSION
};