const OAUTH_CLIENT_ID = process.env.REACT_APP_GOOGLE_OAUTH_CLIENT_ID;

const SANITY_PROJECT_ID = process.env.REACT_APP_SANITY_PROJECT_ID;
const SANITY_TOKEN = process.env.REACT_APP_SANITY_TOKEN;
const SANITY_TOKEN_ALL_ACCESS = process.env.REACT_APP_SANITY_TOKEN_ALL_ACCESS;
const SANITY_DATAESET = process.env.REACT_APP_SANITY_DATAESET;
const SANITY_API_VERSION = process.env.REACT_APP_SANITY_API_VERSION;

const TWITTER_KEY = process.env.REACT_APP_TWITTER_API_KEY;
const TWITTER_SECRET = process.env.REACT_APP_TWITTER_API_KEY_SECRET;

const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN;
const FIREBASE_PROJECT_ID = process.env.REACT_APP_FIREBASE_PROJECT_ID;
const FIREBASE_STORAGE_BUCKET = process.env.REACT_APP_FIREBASE_STORAGE_BUCKET;
const FIREBASE_MESSAGING_SENDER_ID = process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = process.env.REACT_APP_FIREBASE_APP_ID;
const FIREBASE_MESSAGING_VAPID_KEY = process.env.REACT_APP_FIREBASE_MESSAGING_VAPID_KEY;

export {
  OAUTH_CLIENT_ID, 

  SANITY_PROJECT_ID, 
  SANITY_TOKEN,
  SANITY_TOKEN_ALL_ACCESS,
  SANITY_DATAESET,
  SANITY_API_VERSION,
  
  TWITTER_KEY,
  TWITTER_SECRET,

  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MESSAGING_VAPID_KEY
};